 version: '3.7'
 services:
   app:
       build:
         context: .
         dockerfile: Dockerfile
       restart: unless-stopped
       env_file:
         - ".env"
       ports:
         - "5060:5060"
       logging:
         driver: "json-file"
         options:
           max-size: "256m"
           max-file: "10"
