 version: '3.8'
 services:
   app:
       build:
         context: .
         dockerfile: Dockerfile
       restart: unless-stopped
       env_file:
         - ".env"
       ports:
         - "5060:5060"
       logging:
         driver: "json-file"
         options:
           max-size: "256m"
           max-file: "10"
       healthcheck:
         test: [ "CMD", "curl", "-f", "http://0.0.0.0:5060/system/healthcheck" ]
         interval: 5s
         timeout: 10s
         retries: 3
         start_period: 10s